version: '3'
services:
    yolox_compile:
      container_name: $CONTAINER_NAME
      image: 'xilinx/vitis-ai-pytorch-gpu-yolox:3.0.0.007'
      shm_size: 16G
      environment:
        - GID=1000
        - UID=1000
        - NVIDIA_VISIBLE_DEVICES=all
      volumes:
        - '../../:/workspaces'
        - '$WEIGHT_FILE:/FNNQuantedModel_int.xmodel'
        - '$ARCH_FILE:/arch.json'
        - '$OUTPUT_FOLDER:/output'
        - '$UPLOAD_FOLDER:/upload'
      working_dir: /workspaces
      entrypoint: '/bin/bash docker/02_compile/run.sh'
      network_mode: host
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: "nvidia"
      #           count: "all"
      #           capabilities: ["gpu"]
